/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.13/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    java
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation("org.json:json:20210307")
    implementation("org.apache.spark:spark-core_2.12:3.5.6")
    implementation("org.apache.spark:spark-sql_2.12:3.5.6")
   
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
    }
}

application {
    // Define the main class for the application.
    mainClass = "FeedReaderMain"
    
    applicationDefaultJvmArgs = listOf(
        "--add-exports=java.base/sun.nio.ch=ALL-UNNAMED"
    )
}
